### ISSUE TITLE
NIX Sigma 3.0rc2 hangs up (again)

### ISSUE THREAD

**Issue by Knightofthebooks** [NixPlatform/NixCore#35] opened 2019-05-16 04:11 UTC
Debug log below.

Issue: 
Started wallet. Ghosted 5000 Nix. After confirmation unghosted successfully 4000 Nix. After that tried to unghost 50 Nix --> wallet hangs up.

After restarting wallet the Ghost Vault shows 0 ghosted Nix (showing 1000 ghosted Nix would be correct).

W10 x64

![ghosted incorrect](https://user-images.githubusercontent.com/50663678/57825959-73568200-77a1-11e9-938d-339b9fad747f.jpg)

Debug log:
[nix debug 2.log](https://github.com/NixPlatform/NixCore/files/3185351/nix.debug.2.log)

**Comment by mattt21** [comment] 2019-05-16 05:05
Duplicate of #33

**Closed by mattt21** 2019-05-16 05:05 UTC
